# Generated by Django 2.0.13 on 2019-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
